In [38]:
import pandas as pd

In [39]:
data = pd.read_csv("data/2021Census_G01_VIC_SAL.csv")
data = data[["SAL_CODE_2021", "Tot_P_P"]]
data["SAL_CODE_2021"] = data["SAL_CODE_2021"].str.slice(3)
data

     SAL_CODE_2021  Tot_P_P
0            20001        4
1            20002     9088
2            20003     3925
3            20004        7
4            20005      146
...            ...      ...
2941         22942       49
2942         22943      147
2943         22944        0
2944         29494     9089
2945         29797       38

[2946 rows x 2 columns]

In [40]:
suburb_names = pd.read_excel("data/SAL_2021_AUST.xlsx")
suburb_names

,MB_CODE_2021,SAL_CODE_2021,SAL_NAME_2021,STATE_CODE_2021,STATE_NAME_2021,AUS_CODE_2021,AUS_NAME_2021,AREA_ALBERS_SQKM,ASGS_LOCI_URI_2021
0,11018270000,10001,Aarons Pass,1,New South Wales,AUS,Australia,1.4649,http://linked.data.gov.au/dataset/asgsed3/MB/1...
1,11205238700,10001,Aarons Pass,1,New South Wales,AUS,Australia,7.4033,http://linked.data.gov.au/dataset/asgsed3/MB/1...
2,10521602000,10001,Aarons Pass,1,New South Wales,AUS,Australia,27.9213,http://linked.data.gov.au/dataset/asgsed3/MB/1...
3,10521610000,10001,Aarons Pass,1,New South Wales,AUS,Australia,43.5930,http://linked.data.gov.au/dataset/asgsed3/MB/1...
4,11205199200,10001,Aarons Pass,1,New South Wales,AUS,Australia,2.3814,http://linked.data.gov.au/dataset/asgsed3/MB/1...
...,...,...,...,...,...,...,...,...,...
368281,90000009499,99494,No usual address (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...
368282,97000001777,99797,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...
368283,97000002777,99797,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...
368284,97000003777,99797,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...
368285,ZZZZZZZZZZZ,ZZZZZ,Outside Australia,Z,Outside Australia,ZZZ,Outside Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/Z...

In [41]:
suburb_names = suburb_names[suburb_names["STATE_NAME_2021"] == "Victoria"]
suburb_names = suburb_names[["SAL_CODE_2021", "SAL_NAME_2021"]].drop_duplicates()
suburb_names["SAL_NAME_2021"] = suburb_names["SAL_NAME_2021"].str.removesuffix(" (Vic.)").str.upper()
suburb_names

       SAL_CODE_2021                    SAL_NAME_2021
112738         20001                         ABBEYARD
112740         20002                       ABBOTSFORD
112854         20003                       ABERFELDIE
112902         20004                        ABERFELDY
112903         20005                          ACHERON
...              ...                              ...
201462         22942                          YUULONG
201463         22943                          ZEERUST
201466         22944                        ZUMSTEINS
201469         29494                 NO USUAL ADDRESS
201470         29797  MIGRATORY - OFFSHORE - SHIPPING

[2946 rows x 2 columns]

In [44]:
data = data.merge(suburb_names, on="SAL_CODE_2021")
data = data[["SAL_NAME_2021", "Tot_P_P"]]
data = data.rename(columns={"SAL_NAME_2021": "Suburb", "Tot_P_P": "Population"})
data

                               Suburb  Population
0                            ABBEYARD           4
1                          ABBOTSFORD        9088
2                          ABERFELDIE        3925
3                           ABERFELDY           7
4                             ACHERON         146
...                               ...         ...
2941                          YUULONG          49
2942                          ZEERUST         147
2943                        ZUMSTEINS           0
2944                 NO USUAL ADDRESS        9089
2945  MIGRATORY - OFFSHORE - SHIPPING          38

[2946 rows x 2 columns]

In [45]:
data.to_csv("data/population_by_suburb.csv", index=False)